site_name: Articles
site_description: Technical Writing and Language Learning
theme: material

nav: 
 - Home: index.md
 - About: About.md
 - Article 1: Article1.md
 - Article 2: Article2.md
 - Article 3: Article3.md
 - Article 4: Article4.md

