site_name: Articles
site_description: Technical Writing and Language Learning
theme: material

nav: 
 - Home: index.md
 - About: About.md
 - Cross Review: Article1.md
 - Feature Documentation: Article2.md
 - Interviewing: Article3.md
 - About Learning Languages: Article4.md

